version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/socialapp
      JWT_SECRET: supersecret
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && node dist/server.js"

volumes:
  pgdata: